/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "led.h"
#include "button.h"

int main(void)
{
	LedControl_Init();
	Button_Init();

	while(1)
	{
		while (Button_GetLogicInputPin(BUTTON_BOARD_ID) == 0)
		{
			LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 100);
			if (Button_GetLogicInputPin(BUTTON_BOARD_ID) == 1) LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 00);
		}
	}
}
