/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "LightDependentResistor.h"
#include "led.h"
#include "system_stm32f4xx.h"
#include "lightsensor.h"

void LedControl_AutoBrightness(float light);

int main(void)
{
	float light_value;

	SystemCoreClockUpdate();

	LedControl_Init();
	LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 0);
	LightSensor_Init(ADC_READ_MODE_DMA);
	LDR_init(GL5537_1);

	while (1)
	{
		light_value = LDR_getCurrentLux(LightSensor_MeasureUseDMAMode());

		LedControl_AutoBrightness(light_value);
	}

	return 0;
}

void LedControl_AutoBrightness(float light)
{
	if (light < 10) {
		LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 10);
	}
	else if (light >= 10 && light < 25) {
		LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 15);
	}
	else if (light >= 25 && light < 50) {
		LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 30);
	}
	else if (light >= 50 && light < 80) {
		LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 50);
	}
	else if (light >= 80 && light < 120) {
		LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 70);
	}
	else if (light >= 120 && light < 200) {
		LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 90);
	}
	else {
		LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 100);
	}
}
