/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <led.h>

void ledSetState(uint8_t logic);
void delay_ms (uint32_t milisecond);

int main(void)
{
	uint8_t ledLogicToggle;
	LedControl_Init();

	while(1)
	{
		ledSetState(ledLogicToggle |= (1 << 0));
		delay_ms(500);

		ledSetState(ledLogicToggle &= ~(1 << 0));
		delay_ms(500);
	}

}

void ledSetState(uint8_t logic)
{
	if (logic == 1)
	{
		LedControl_SetColorIndividual(LED_KIT_ID1, LED_COLOR_GREEN, 100);
	}
	else
	{
		LedControl_SetColorIndividual(LED_KIT_ID1, LED_COLOR_GREEN, 0);
	}
}

void delay_ms (uint32_t milisecond)
{
	for (uint32_t i = 0; i < milisecond; i++)
	{
		for (uint32_t j = 0; j < 5000; j++);
	}

}
