/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
	float temperature = 33.27;

	printf("Variable's address: %p", &temperature);

	if (temperature < 35)
	{
		printf("OK Lumi! The AC has turned OFF");
	}
	else
	{
		printf("OK Lumi! The AC has turned ON");
	}
	return 0;
}
